# Default values for coredns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: coredns/coredns
  tag: "1.2.0"
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

serviceType: "NodePort"

service:
# clusterIP: ""
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9153"

rbac:
  # If true, create & use RBAC resources
  create: true
  # Ignored if rbac.create is true
  serviceAccountName: default

# isClusterService specifies whether chart should be deployed as cluster-service or normal k8s app.
isClusterService: false

servers:
- zones:
  - zone: .
  port: 53
  plugins:
  - name: cache
    parameters: 30
  - name: errors
  - name: health
  - name: kubernetes
    parameters: cluster.local
  - name: loadbalance
    parameters: round_robin
  - name: prometheus
    parameters: 0.0.0.0:9153
  - name: proxy
    parameters: . /etc/resolv.conf
  - name: file
    parameters: /etc/coredns/example.db example.com
    
# Complete example with all the options:
# - zones:                 # the `zones` block can be left out entirely, defaults to "."
#   - zone: hello.world.   # optional, defaults to "."
#     scheme: tls://       # optional, defaults to "" (which equals "dns://" in CoreDNS)
#   port: 12345            # optional, defaults to "" (which equals 53 in CoreDNS)
#   plugins:               # the plugins to use for this server block
#   - name: kubernetes     # name of plugin, if used multiple times ensure that the plugin supports it!
#     parameters: foo bar  # list of parameters after the plugin
#     configBlock: |-      # if the plugin supports extra block style config, supply it here
#       hello world
#       foo bar

# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#affinity-v1-core
# for example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
affinity: {}

# Node labels for pod assignment
# Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# expects input structure as per specification https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#toleration-v1-core
# for example:
#   tolerations:
#   - key: foo.bar.com/role
#     operator: Equal
#     value: master
#     effect: NoSchedule
tolerations: []

# configure custom zone files as per https://coredns.io/2017/05/08/custom-dns-entries-for-kubernetes/
zoneFiles:
   - filename: example.db
     domain: example.com
     contents: |
      example.com.   IN SOA localhost. root.localhost. 2018110201 7200 3600 1209600 3600
      example.com.   IN NS  localhost.
      *.example.com. IN A   61.218.118.230
